import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { gateBody, prepareGate, OUTPUT } from './prepare-gate.mjs';

test('only leading metadata is removed and a later delimiter remains in the gate body', () => {
  const body = '<!-- coai-snippet v5 -->\n## Multi-model review gate (ConnectOtherAIs)\n\nFirst.\n---\nSecond.\n';
  assert.equal(gateBody('---\nid: common.gate\n---\n' + body), body);
  assert.equal(gateBody(('---\nid: common.gate\n---\n' + body).replaceAll('\n', '\r\n')), body);
  assert.throws(() => gateBody('---\nmissing closing delimiter'), /unterminated/);
  assert.throws(() => gateBody('---\nid: common.gate\n---\nempty'), /missing canonical/);
});

test('the real pinned resolver rejects a dirty or wrong mount and leaves no stale build policy', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'coai-pinned-gate-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const sourceRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const sourceMount = path.join(sourceRoot, '.agents/conventions');
  const git = (cwd, ...args) => execFileSync('git', ['-C', cwd, ...args], {
    encoding: 'utf8', timeout: 30_000, maxBuffer: 1024 * 1024, windowsHide: true,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  const commit = cwd => git(cwd, '-c', 'user.name=Gate fixture', '-c', 'user.email=gate@example.invalid',
    '-c', 'commit.gpgsign=false', 'commit', '--allow-empty', '-qm', 'fixture');
  git(root, 'init', '-q');
  git(root, '-c', 'protocol.file.allow=always', 'submodule', 'add', '-q', sourceMount, '.agents/conventions');
  const mount = path.join(root, '.agents/conventions');
  fs.symlinkSync(path.join(sourceMount, 'node_modules'), path.join(mount, 'node_modules'), process.platform === 'win32' ? 'junction' : 'dir');
  fs.copyFileSync(path.join(sourceRoot, 'AGENTS.md'), path.join(root, 'AGENTS.md'));
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), '@AGENTS.md\n');
  fs.writeFileSync(path.join(root, '.agents/PROJECT.md'), '# Fixture project\n');
  git(root, 'add', 'AGENTS.md', 'CLAUDE.md', '.agents/PROJECT.md');
  commit(root);
  const output = path.join(root, OUTPUT);
  const body = prepareGate(root);
  assert.ok(fs.readFileSync(output, 'utf8').includes(JSON.stringify(body)), 'generated bytes contain the canonical body');
  // Generated artifacts are ignored in the product; keep this fixture equivalent.
  fs.writeFileSync(path.join(root, '.gitignore'), 'src_vs_code/src/generated/\n');
  const rule = path.join(mount, 'common/coai-review-gate.md');
  const original = fs.readFileSync(rule);
  fs.appendFileSync(rule, '\nUnreviewed edit.\n');
  assert.throws(() => prepareGate(root), /uncommitted changes/i);
  assert.equal(fs.existsSync(output), false);
  fs.writeFileSync(rule, original);
  prepareGate(root);
  commit(mount);
  assert.throws(() => prepareGate(root), /pin|gitlink|mismatch/i);
  assert.equal(fs.existsSync(output), false);
});

test('missing canonical checkout fails preparation and invalidates previous generated policy', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'coai-prepare-gate-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const output = path.join(root, OUTPUT);
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, 'previous generated policy');
  assert.throws(() => prepareGate(root), /git submodule update --init/);
  assert.equal(fs.existsSync(output), false);
});
