// GENERATED FILE — do not edit by hand.
//
// Written by `node scripts/generate-command-texts.mjs` from `shared/commands/*.md`, the texts coai-mcp
// embeds. Edit a text there and run the script; `commandTexts.test.ts` fails if this file and the
// folder disagree.

/** The gate's shipped command texts, by id — what an override replaces and Restore brings back. */
export const SHIPPED_COMMAND_TEXTS: Readonly<Record<string, string>> = {
  "command-already-split-epic": ", so do NOT split it again: build it as one unit, review its diff through this gate, fix, document, test and commit. If it is genuinely too big for one unit, say so in your summary and say what you would have cut it into — but do not start a second round of splitting on your own.",
  "command-already-split-task": ", so do NOT split it again — and it is not gated on its own: the task is gated once as a whole, so build it on the task's branch, commit it as ONE commit, and leave the review to the single code round at the end of the task. If this is in fact a NEW task rather than a piece of the one you split, gate it as usual: build it, review its diff through this gate, fix, document, test and commit.",
  "command-another-code-round": "A resolved code round closes the session: for a checkpoint, a final round after one, or a retry after a crash, commit the new work and call review_code with again: true.",
  "command-autonomy": "Say that you are working autonomously, and keep saying what you are writing right now as you go. Autonomous means these orders, not a mood: (1) every bug and every problem spot gets a RED-GREEN-RED test — a failing test first, then the fix, then the test green, then a check that the test really fails without the fix; (2) the documentation is updated with every change — the README, the manifest if there is one, the module docs and every other file that describes what you changed; (3) before any release, run ALL the tests that exist, not only the ones near your change; (4) if the repository has a release or pull request process, do it — and on a pull request, wait about five minutes, then check whether automatic comments appeared, read them and fix what they name; (5) if a deploy triggers automatically, verify the result against the target environment — dev, stage or test — and read its logs for errors before calling it done; (6) re-read your own code against the repository's rules and follow them, not only the ones you remember. A question that does not block you is not asked now: write it down and put every one of them at the END of your final summary. A question that DOES block you is asked at once — but before you ask it, {scope} and gather every other blocking question you can foresee, so the person is interrupted once with all of them rather than repeatedly with one. Where you can proceed under a stated assumption, do that instead of asking, and say what you assumed.",
  "command-cadence-epic": "per EPIC, never per story: give each epic its own branch, starting from the previous epic's commit; call review_plan with that epic's plan; build all of its stories without gating them one by one; COMMIT the epic, then run review_code over the epic's whole diff, with the previous epic's commit as baseRef — it reviews committed changes only, and an uncommitted epic is refused as nothing to review; resolve every finding, fix what you accepted, update the documentation and the tests, and fold the fixes into the epic's ONE commit. Only then start the next epic.",
  "command-cadence-single": "for this work, never per story: build it on this branch without gating each piece; COMMIT it, then run review_code over the whole diff — it reviews committed changes only, and uncommitted work is refused as nothing to review; resolve every finding, fix what you accepted, update the documentation and the tests, and fold the fixes into that ONE commit.",
  "command-cadence-task": "for the WHOLE task, never per epic or story: this plan round was its plan gate; build every epic and its stories on this branch without gating them, and commit each epic as ONE commit as you finish it; then ONE review_code over the whole task's diff; resolve every finding, fix what you accepted, update the documentation and the tests, and commit.",
  "command-model": "{strongest} at its highest available version — deciding what the epics and stories are is the judgement that shapes everything after it. Then implement: ordinary stories on {implementation}, and anything where being wrong is expensive — payments, money, authentication, security, architecture, data migration — on {strongest} (max) again. Name the model you used for each story in your summary.",
  "command-preamble": "COMMANDS from the operator of this gate. They come from switches a person set in the panel and they outrank your own defaults for this task. Follow them, and say in your summary which ones you applied.",
  "command-split-huge": "Split this plan into 4-5 EPICS, each of 3-5 logically complete STORIES. Fewer is fine when the work is smaller; never more.",
  "command-split-large": "Split this plan into 3-4 EPICS, each of 3-4 logically complete STORIES. Fewer is fine when the work is smaller; never more.",
  "command-split-measured": "(Measured from the plan you sent: {numbers} — size {verdict}. That is a heuristic — if it is wrong for this plan, say so in your summary and do what is right.)",
  "command-split-medium": "Split this plan into 2-3 EPICS, each of 2-3 logically complete STORIES. Fewer is fine when the work is smaller; never more.",
  "command-split-none": "This plan is small enough to build as it stands; split it only if you disagree, and say why.",
  "command-split-small": "Split this plan into 3-5 logically complete STORIES — no epics. Fewer is fine when the work is smaller; never more.",
};
