// GENERATED by scripts/generate-credential-words.mjs from shared/credential-words.json.
// Do not edit. Run the script; `generatedFilesAreCurrent.test.ts` fails when this is behind.
//
// The server embeds the same JSON (CoaiMcp.Core.csproj) and refuses to start without it. Neither
// half reads `shared/` at run time: a published binary and an installed VSIX have no such
// directory, and a redactor that fell back to an empty list there would write raw credentials.

/** Words that mean a credential wherever they appear inside a name. */
export const ANYWHERE: readonly string[] = [
  'token',
  'secret',
  'password',
  'passwd',
  'authorization',
  'credential',
  'signature',
  'apikey',
  'accesskey',
  'privatekey',
];

/** Words that mean a credential only when they are a WHOLE part of the name. */
export const WHOLE_PART: readonly string[] = [
  'key',
  'auth',
  'sig',
];
