import { HelpBody } from './helpContent';

/**
 * The help catalog in Spanish.
 *
 * <p>A file per language: a translation pass is then reviewable on its own, and eighteen articles
 * in five languages inline would be one literal nobody could edit without breaking a quote. A key
 * that is missing here falls back to the English body, visibly — see `bodyFor`.</p>
 */
export const ES: Readonly<Record<string, HelpBody>> = {
  "install-the-server": {
    title: "Empiece aquí: instale el servidor MCP",
    whatItIs: "La extensión es la cara. Quien hace la revisión es `coai-mcp`, un programa pequeño que arranca su asistente de IA. Mientras no esté instalado, no revisa nadie.",
    why: "Una revisión tiene que ejecutarse donde está su código, lanzar las CLI de los proveedores y trabajar durante minutos. Una extensión de VS Code no puede hacerlo, y un servidor propiedad de una ventana de VS Code moriría con ella.",
    setup: "Abra la sección **Server**. Ahí se ve qué hay instalado, qué hay publicado, y un botón cuando difieren: púlselo. La descarga se verifica contra el `.sha256` de la propia release, el binario va al almacén privado de la extensión y no entra en el `PATH`.\n\nDespués, menú ⋯ → **Copy the MCP config block** y pegue el bloque en la configuración de su asistente. Esto se hace UNA vez. Reinicie el asistente para que levante el servidor.",
    usage: "Después volverá poco a la sección Server: la versión publicada se reconsulta como mucho cada media hora, y **Check again** pregunta ahora mismo.\n\nCada plataforma tiene su propio binario. En cada release se publican compilaciones para Windows, macOS y Linux; una máquina sin la suya lo dice con franqueza en vez de descargar la ajena.",
    whatCanGoWrong: "Si el panel dice que no pudo leer la versión publicada, no se alcanzó GitHub. Nada está roto: el servidor instalado funciona.\n\nSi tras pegar el bloque su asistente no muestra las herramientas, no se ha reiniciado. El bloque lleva la ruta exacta al binario; un bloque copiado de otra máquina apunta a una ruta que aquí no existe.",
  },
  "choose-reviewers": {
    title: "Después: elija quién revisa",
    whatItIs: "La sección **Reviewers** es el reparto de modelos ajenos que leerán su plan y su código. Cada fila es un proveedor: un interruptor, la elección de modelo, ▶ para abrir su CLI en una terminal y **remove**.",
    why: "Todo el sentido está en que el revisor no es el autor. La segunda opinión del mismo modelo que escribió el código vale menos que la primera opinión de otro. Y un hallazgo en el que coinciden dos proveedores es la señal más fuerte que este producto llega a dar.",
    setup: "**＋ Add a reviewer** ofrece los proveedores que esta compilación conoce: Codex, Antigravity (Gemini, Claude y GPT-OSS con una sola suscripción), un segundo Claude, DeepSeek, OpenRouter y una fila en blanco para cualquier endpoint compatible con OpenAI.\n\nLa mayoría se autentican solos: si la CLI ya inició sesión en esta máquina, no hace falta clave. El botón ▶ de la fila abre una terminal con esa CLI — ahí es donde inicia sesión, y ahí ya está escrito su comando de consumo: solo falta pulsar Enter.",
    usage: "Dos revisores son el mínimo útil, porque la señal es la coincidencia. Tres cuestan el triple y rara vez dicen el triple.\n\nLa elección de modelo muestra lo que esa CLI alcanza de verdad en esta máquina: en Codex, su propia caché de modelos; en el resto, una lista curada. **another model…** acepta cualquier id exacto.",
    whatCanGoWrong: "No se puede eliminar el último revisor: un panel sin participantes no revisa nada.\n\nUn proveedor cuya CLI no esté instalada lo dirá en **providers** ANTES de la ronda, no a mitad. Aparte, sobre Gemini: está marcado RETIRED — Google cerró Code Assist para cuentas individuales y esa CLI ahora rechaza antes de llegar a un modelo. Use Antigravity.",
  },
  "teach-your-ai": {
    title: "Y: dígale a su IA que use la puerta",
    whatItIs: "Menú ⋯ → **Copy the CLAUDE.md snippet** da un párrafo que se pega en el repositorio que quiere revisar. Le dice a la IA que trabaja allí que existe una puerta de revisión y en qué orden se usa.",
    why: "Un asistente con herramientas pero sin instrucción no se le ocurre abrir una sesión de revisión. Ese párrafo ES la instrucción, y vive en el repositorio y no en la extensión porque es una propiedad del proyecto, no de su editor.",
    setup: "Cópielo, péguelo en el `CLAUDE.md` de ese repositorio (o en lo que lea su asistente) y haga commit. No nombra ningún repositorio: la IA que lo lee ya está dentro de una copia de trabajo que puede nombrar ella misma.",
    usage: "A partir de ahí el asistente abre una sesión, envía el plan, resuelve los hallazgos, implementa, envía el diff y vuelve a resolver. Usted lo observa en **Recent rounds** y responde a lo que escale.",
    whatCanGoWrong: "Nada obliga a cumplir ese párrafo. El asistente puede ignorarlo, y la puerta no puede llamarse a sí misma. Lo que SÍ puede es negarse a revisar código mientras el plan no haya pasado, y eso lo hace.",
  },
  "the-gate": {
    title: "La puerta: rondas, umbral y qué hacer cuando se agotan",
    whatItIs: "Tres ajustes deciden cuándo termina una revisión. **Rounds per stage**: cuántos intentos recibe una etapa. **Passes at or under**: cuántos hallazgos bloqueantes son admisibles. **When the rounds run out**: qué hacer si no bastó.",
    why: "Sin límite, el bucle de revisión no acaba nunca: siempre aparece un hallazgo más. El umbral pone un número a lo que significa «suficiente» antes de que empiece la discusión.",
    setup: "Por defecto: tres rondas, umbral dos y *Ask a human*. Al umbral solo cuentan los hallazgos **blocking** y **major**; minor y nit no bloquean nunca.\n\nUn hallazgo levantado por dos proveedores cuenta UNA vez. Un hallazgo que usted rechazó con motivo deja de contar hasta que un revisor lo vuelva a plantear con un argumento nuevo.",
    usage: "*Ask a human* es el valor por defecto honesto: la puerta se detiene y le pone la decisión delante. *Continue anyway* sigue y dice en voz alta que quedaron hallazgos. *Escalate* sube la escalera — más esfuerzo del revisor, luego un modelo revisor más fuerte, luego un árbitro más fuerte — y cada vez le da a la etapa un juego nuevo de rondas.",
    whatCanGoWrong: "Un umbral de cero significa que bloquea cualquier hallazgo de cualquier gravedad: la revisión no pasará nunca.\n\nLas rondas se cuentan POR ETAPA: el plan y el código tienen cada uno su juego completo.",
  },
  "prompts-per-round": {
    title: "Prompts por ronda y rotación automática",
    whatItIs: "Cada rol de revisor tiene un prompt universal y dos lentes estrechas. Esta sección elige qué prompt usa cada RONDA, por rol — o deja que las rondas los recorran automáticamente.",
    why: "Un prompt por rol para siempre es el valor por defecto correcto y el techo equivocado. Cuando a un modelo se le pide mirar todo, se dispersa, y una segunda ronda de la misma pregunta amplia suele devolver las mismas respuestas amplias.",
    setup: "Una elección por ronda para cada rol; el propósito de cada opción está en su tooltip. **Rotate the lenses automatically** gasta la primera ronda en la pregunta universal y cada siguiente en otra lente. Una elección explícita siempre gana a la rotación.\n\nUna ronda que no haya tocado queda sin fijar, y la rotación sigue aplicándose a ella.",
    usage: "La rotación viene DESACTIVADA, y es una decisión, no cautela. Medida contra el prompt universal en dos rondas de código, dio MENOS hallazgos distintos (17 frente a 25) por menos dinero.\n\nLos textos completos están en el artículo **Prompts completos**.",
    whatCanGoWrong: "**Lo que la medición no demuestra.** En tres planes, la unión de las tres lentes encontró aproximadamente el doble que cualquiera por separado — y ese resultado no sobrevivió a su propio control: el mismo prompt sobre el mismo texto dio tres veces 6, 4 y 5 hallazgos, con solapamientos de 3, 1 y cero. La dispersión del modelo lo explica todo por sí sola. Las lentes se ofrecen como forma de apuntar, no como forma demostrada de encontrar más.",
  },
  "limits": {
    title: "Límites: cuántos a la vez y cuánto se espera a cada uno",
    whatItIs: "**Reviewers at once** limita todo el abanico. **Per vendor** limita a un proveedor. **Reviewer timeout**: cuánto puede tardar un revisor. **Wait for you**: cuánto espera una escalada a una persona antes de rendirse.",
    why: "Una ronda de código son seis procesos que quieren arrancar en el mismo segundo: tres roles por dos proveedores. Sin límite, es justo aquí donde llegan a la vez los límites de procesos del sistema, los ficheros de bloqueo de las propias CLI y los límites de los proveedores — y cada uno parece un timeout mientras no se le llame por su nombre.",
    setup: "Por defecto, tres a la vez y dos por proveedor. El límite por proveedor existe porque el límite de peticiones se cuenta por proveedor: un único límite global gastaría tranquilamente todas las plazas en uno solo.\n\nEl timeout del revisor es de diez minutos. Una ronda de código sobre un diff grande tarda de tres a cinco.",
    usage: "Suba el límite global en una máquina con núcleos libres y bájelo en el portátil en el que además está trabajando. Quien choque contra los límites del proveedor debe bajar precisamente el límite POR PROVEEDOR.",
    whatCanGoWrong: "El timeout mata todo el árbol de procesos, no solo la CLI: los hijos de un revisor no le sobreviven.\n\nQue expire **Wait for you** no es una negativa: la escalada sigue abierta en el panel, y la IA recibe la instrucción de preguntarle en la conversación.",
  },
  "language-and-translator": {
    title: "Idioma: aquel en el que le preguntan",
    whatItIs: "**Ask and answer in** es el idioma en el que la pregunta le llega, y el idioma DESDE el que se traduce de vuelta su respuesta. **Translated by** decide qué modelo pequeño y rápido lo hace.",
    why: "La IA que pregunta suele escribir en inglés. Usted no debería tener que leerlo, y ella no debería tener que descifrar su respuesta en otro idioma para actuar en consecuencia.",
    setup: "Elija su idioma. El traductor por defecto es un modelo rápido, porque hace un trabajo de una frase mientras usted espera. **Nobody — always show the original** desactiva la traducción.",
    usage: "La traducción va en ambos sentidos: la pregunta a su idioma, su respuesta de vuelta al idioma en que se preguntó. Sus propias palabras se conservan siempre junto a la traducción, así que en ella no se pierde nada.",
    whatCanGoWrong: "Un traductor que no pudo arrancar muestra el original con una nota, no un vacío. Una pregunta en el idioma equivocado es una molestia; una pregunta desaparecida detiene la revisión.",
  },
  "vendor-keys": {
    title: "Claves de proveedor: solo cuando una CLI no sabe autenticarse sola",
    whatItIs: "Una única entrada de tipo `config` en CredsForDevs que guarda una clave por cada proveedor que la necesite. El panel muestra cuál de sus revisores la necesita de verdad.",
    why: "La mayoría de las CLI de revisor ya tienen sesión iniciada en su máquina y no necesitan clave alguna. Quienes sí la necesitan — un endpoint propio, DeepSeek, OpenRouter — no deberían teclearla en un fichero de ajustes.",
    setup: "Solo hace falta si la fila del revisor lo dice. Cree una entrada `config` en CredsForDevs, guarde ahí las claves como `{\"deepseek\": \"sk-…\"}` y pegue su identificador en **CredsForDevs config key**.",
    usage: "El servidor lee la entrada al arrancar y pasa cada clave a su proveedor por el entorno, nunca por la línea de comandos. Cambiar una clave surte efecto en el siguiente arranque del servidor.",
    whatCanGoWrong: "Un proveedor que necesita clave y no la tiene aparece en **providers** como `unavailable` con su motivo y se cae del abanico — no se salta en silencio.",
  },
  "recent-rounds": {
    title: "Recent rounds: qué hubo y qué está pasando ahora",
    whatItIs: "Las últimas rondas, las recientes arriba, y la que está en curso siempre primera. En la fila: qué se revisó, la etapa, el veredicto, el número de hallazgos bloqueantes, el tiempo y el gasto.",
    why: "Una revisión tarda minutos. Sin esto, el panel no distinguiría «seis revisores trabajando» de «aquí no se ha ejecutado nunca nada», y habría que bajar al log.",
    setup: "Nada que configurar. El servidor escribe la ronda en disco en el momento de arrancarla y la actualiza a medida que avanzan los revisores, así que la imagen sobrevive a recargar la ventana, reiniciar la extensión y matar el servidor.",
    usage: "La ronda en curso muestra sus revisores y qué hace cada uno. **Show review rounds** en el menú ⋯ abre lo mismo como fichero, que puede dejar abierto junto al trabajo: se reescribe según avanzan las rondas.",
    whatCanGoWrong: "Una ronda abandonada por un servidor caído se lee como *interrupted*, no como «lleva ejecutándose para siempre». Las rondas escritas por un servidor antiguo pueden no tener gasto ni tema: entonces no se guardaban, y rellenarlo a posteriori sería inventarlo.",
  },
  "what-each-ai-has-used": {
    title: "What each AI has used: tokens, dinero y tiempo",
    whatItIs: "Una barra por proveedor para el día, la semana, el mes o el año: tokens de entrada y salida, dinero, número de ejecuciones, cuántas fallaron, tiempo total y medio, y el total general.",
    why: "Un panel de revisión gasta dinero real en cada ronda, y la pregunta «cuánto ha costado este mes» no la responde un fichero de sesión: las sesiones se reescriben durante las rondas y cada una sostiene una rama.",
    setup: "Nada que configurar. El servidor añade una línea por revisor a `usage.jsonl` en su directorio de datos, y esta sección la lee.",
    usage: "**Un revisor que falla también cuenta.** Una ejecución que quemó noventa segundos y no respondió nada es exactamente lo que un registro de gasto no debe esconder; por eso cada línea tiene un desenlace y el número de fallos va junto a los tokens.\n\nEn el dinero hay un guion allí donde el proveedor no se tarifica a sí mismo: «gratis» y «no informado» son hechos distintos, y solo uno de ellos es una buena noticia. El dinero lo informa Claude; Codex y Antigravity solo informan tokens.",
    whatCanGoWrong: "Los tokens se cuentan según las reglas de cada proveedor, porque una única regla común sería falsa al menos para uno: en Codex la caché va DENTRO de los tokens de entrada, en Claude se suma a ellos, y en Antigravity los tokens de razonamiento están dentro de los de salida. Claude además informa de la misma ejecución dos veces y de forma distinta; se toma el agregado.",
  },
  "questions-waiting": {
    title: "Una pregunta que le espera",
    whatItIs: "Cuando la puerta necesita a una persona, arriba del panel aparece una tarjeta con la pregunta y los hallazgos que siguen bloqueando. Se abre un diálogo, aparece un elemento en la barra de estado y el icono del título se pone verde.",
    why: "Detrás de esa pregunta hay una ronda BLOQUEADA. Una notificación que se puede perder no sirve para esto — de ahí las tres superficies, y cerrar el diálogo no pierde nada.",
    setup: "Nada que configurar. El servidor escribe la pregunta como fichero en el directorio que la extensión ya vigila: ninguna de las dos mitades abre un puerto.",
    usage: "Puede responder en el panel, en el diálogo o desde la barra de estado: es la misma acción. La respuesta va a la IA que preguntó, traducida al idioma en que preguntó, y sus propias palabras se conservan al lado.",
    whatCanGoWrong: "El veredicto `call_human` también levanta una tarjeta así, de modo que una puerta con las rondas agotadas le alcanza aunque la IA calle. No siempre fue así: antes el veredicto era una instrucción solo para la IA, y una persona podía mirar el panel todo el día sin enterarse de que la habían llamado.",
  },
  "prompts-in-full": {
    title: "Prompts completos",
    whatItIs: "El texto íntegro de cada prompt que el producto envía a un revisor: cuatro universales y ocho lentes estrechas. Aquí no se resume nada: esto es lo que lee el modelo.",
    why: "Una revisión que no se puede comprobar hay que creerla. Conocer la formulación exacta de la pregunta es lo único que permite juzgar si una respuesta es justa, y si un hallazgo con el que no está de acuerdo viene de un mal modelo o de una mala pregunta.",
    setup: "Nada que configurar. Lo impreso abajo se contrasta con un test contra los propios ficheros de prompts del servidor, así que no puede divergir de lo que realmente se ejecuta.",
    usage: "Todos los prompts terminan con la misma disciplina: un hallazgo debe nombrar una situación concreta y un resultado incorrecto, cuatro clases de no-hallazgos están nombradas y prohibidas, y la lista vacía se declara una respuesta admisible — a un revisor al que se le ordena encontrar siempre algo, siempre encuentra algo.\n\nCualquiera se puede sobrescribir: ponga un fichero con el nombre del prompt en la carpeta `prompts/` dentro del directorio de datos del servidor y regirá mientras exista. Bórrelo y vuelve el texto de serie.",
    whatCanGoWrong: "Una sobrescritura no se valida. Un prompt que no exija el esquema de hallazgos dará respuestas que nadie puede parsear, y la ronda informará de ese revisor como ilegible — guardando su respuesta en bruto en disco para que vea qué se preguntó exactamente.",
  },
  "the-help-page": {
    title: "Esta página: búsqueda, idioma y tamaño del texto",
    whatItIs: "El ? amarillo del título del panel abre esta ayuda. La lista muestra cada artículo con su primera línea; el campo de arriba busca en todos; el desplegable cambia el idioma; los botones ± cambian el tamaño del texto.",
    why: "Un panel de ajustes con dieciséis elementos necesita un sitio donde se diga qué hace cada uno — un tooltip no sirve. El tamaño del texto está aquí porque la vista no es materia de discusión: cinco pasos en cada sentido son aproximadamente ×1,6 arriba o abajo.",
    setup: "Nada que configurar. El selector de idioma escribe `coai.helpLanguage` y solo afecta a estas páginas — no es el idioma en el que se pregunta a sus revisores, ese está en la sección **Language**. Los botones ± escriben `coai.uiScale`. Ambos son ajustes reales, así que se sincronizan con sus otras máquinas.",
    usage: "La búsqueda recorre los títulos Y el texto completo de cada artículo en el idioma mostrado, así que una palabra que recuerde de un párrafo encuentra el artículo donde estaba. Escape cierra un artículo y vuelve a la lista, y Back conserva lo escrito.\n\nUn artículo sin traducir muestra el inglés con una nota visible, no una página en blanco.",
    whatCanGoWrong: "Que una traducción vaya por detrás del inglés es normal y se señala. Lo que no puede pasar es que falte un artículo: un test de cobertura tumba la compilación cuando de un comando o un ajuste no hay nada escrito. Justo por eso esta página no puede convertirse en silencio en la descripción de un producto que ya no existe.",
  },
  "the-protocol": {
    title: "Bajo el capó: el protocolo que sigue su IA",
    whatItIs: "Siete herramientas en orden estricto. `open` abre una sesión para un repositorio y una rama. `review_plan` envía el plan a todos los revisores. `resolve` registra la aceptación o el rechazo de CADA hallazgo. `review_code` hace lo mismo con el diff, con tres roles por proveedor. `providers` muestra el estado, `status` devuelve al contexto una conversación reanudada, y `ask_human` escala hasta usted.",
    why: "El orden se sostiene por rechazo, no por buena conducta: `review_code` se niega mientras ninguna ronda de plan haya llegado a *proceed*, de modo que saltarse una etapa es imposible, no «desaconsejable».",
    setup: "Nada que configurar: esto lo maneja su IA. El orden se lo dice justo el fragmento que usted pegó en el repositorio.",
    usage: "Un rechazo exige un motivo, y el motivo se conserva: un hallazgo rechazado no cuenta en las siguientes rondas hasta que un revisor lo vuelva a plantear con un argumento nuevo. Eso es lo que impide que el bucle reabra una decisión que usted ya tomó.",
    whatCanGoWrong: "Una ronda en la que no respondió NADIE no pasa nunca. Un resultado vacío es ausencia de evidencia, no evidencia de ausencia: la puerta llama a una persona en su lugar. Es el único caso en el que «sin hallazgos» no debe significar «aprobado».",
  },
  "where-reviewers-run": {
    title: "Bajo el capó: dónde se ejecuta realmente un revisor",
    whatItIs: "La etapa de código da a la ronda UN git-worktree, fijado al commit de la rama, solo lectura. La etapa de plan da en cambio a cada revisor un directorio VACÍO.",
    why: "Si a una CLI agéntica se le da un repositorio y un plan que menciona ficheros, va a leerlos. Medido: ocho minutos y aún ejecutándose — sobre un documento de quince kilobytes. Ahí el papel es juzgar el DOCUMENTO; el repositorio lo necesita la etapa de código.",
    setup: "Nada que configurar. Los worktrees viven en el directorio de datos del servidor y se limpian al abrir una sesión, así que una ronda abortada no deja nada detrás.",
    usage: "Lo que cuesta el directorio vacío, sin rodeos: un revisor de plan no puede comprobar que una referencia del tipo `file.cs:line` sea real. Esa comprobación nunca estuvo en el prompt del plan, y comprarla al precio de diez veces el tiempo es el cambio equivocado para una puerta en la que hay una persona esperando.",
    whatCanGoWrong: "El único reintento de un revisor también se ejecuta en un directorio vacío, por la misma razón: la reparación pide la respuesta con el esquema, no una investigación nueva. Precisamente volver a entregarle un checkout costaba un revisor en una de cada tres rondas de código.",
  },
  "when-a-reviewer-fails": {
    title: "Bajo el capó: qué pasa cuando un revisor falla",
    whatItIs: "Seis desenlaces con nombre, y nunca un cero silencioso: respondió, agotó el tiempo, terminó con código distinto de cero, chocó con un límite, no pudo arrancar, o respondió algo que no se puede parsear. Una ronda que pasó con cuatro revisores de seis lo dice así, con nombres.",
    why: "Un panel que no revisó no es un panel que aprobó. Cada ronda incompleta se informa como incompleta, y la frase sobre los revisores nombra quién falló y por qué.",
    setup: "Nada que configurar. Un revisor con límite de peticiones se reintenta una sola vez tras una pausa — salvo que el proveedor haya dicho que el límite es DIARIO, y eso no lo cura ningún reintento.",
    usage: "Una negativa lleva las propias palabras de la CLI, elegidas por contenido y no por posición: la primera línea que anuncia un error, saltándose los marcos de pila y los banners de versión. Para cinco negativas conocidas — CLI cerrada, directorio no confiable, binario ausente para la plataforma — se dice QUÉ HACER, no qué se imprimió.",
    whatCanGoWrong: "Una respuesta que no se pudo parsear se guarda en disco bajo `unparseable/` dentro del directorio de datos, y la negativa nombra el fichero. Esto nació porque esa misma respuesta, reproducida a mano, pasaba sin problemas: el mensaje nombraba un síntoma imposible de investigar.",
  },
  "settings-and-the-server": {
    title: "Bajo el capó: cómo llega un ajuste al servidor",
    whatItIs: "El panel escribe sus ajustes en un fichero dentro del directorio de datos del servidor, y el servidor relee ese fichero cada vez que cambia.",
    why: "Antes los ajustes llegaban al servidor solo dentro del bloque de configuración pegado, y cambiar un umbral se convertía en un trámite: copiar el bloque, encontrar la configuración del cliente, pegar, reiniciar. Y solo se aplicaban al arrancar — una brecha invisible desde ambos lados, porque el panel guarda al instante y así lo dice.",
    setup: "Nada que configurar. Un cambio en el panel rige desde la SIGUIENTE ronda: ni reinicio ni volver a pegar.",
    usage: "Una variable puesta en la configuración del propio asistente sigue ganando al fichero: es más específica que un fichero que cualquier ventana puede reescribir.\n\nEl panel escribe solo lo que DIFIERE de los valores por defecto, así que devolver un ajuste a su valor por defecto lo quita del fichero en vez de fijarlo.",
    whatCanGoWrong: "Un fichero a medio escribir deja en pie la última configuración que funcionaba. Una lectura rota que diera una lista de proveedores vacía habría hecho fallar a todos los revisores y lo habría informado un panel de acuerdo consigo mismo.",
  },
  "the-audit-log": {
    title: "Bajo el capó: el registro de auditoría",
    whatItIs: "Un fichero de log por arranque del servidor, junto al binario instalado, en `logs/<día>/`. Contiene el reparto de cada ronda, el arranque y la respuesta de cada revisor con tokens y dinero, cada negativa como aviso con su motivo, y cada hallazgo con su procedencia.",
    why: "El resumen de una ronda es deliberadamente una frase, y una frase no responde a «por qué falló ese revisor». Esa pregunta surgió dos veces en una puerta real, y las dos veces no había nada que responder.",
    setup: "Nada que configurar. Los niveles vienen de la configuración y no de los puntos de llamada, y cada arranque escribe un fichero nuevo — no uno por día, porque casi siempre se pregunta qué hizo AQUELLA ejecución.",
    usage: "En nivel debug se escribe la línea de comandos exacta de cada revisor: esa es la diferencia entre «saber que se preguntó al proveedor» y «pegar el comando en una terminal y ver la misma negativa».",
    whatCanGoWrong: "El log es el único sitio donde algunas cosas quedan registradas. No rota ni se recorta: un año de trabajo denso es una carpeta de ficheros pequeños — no es un problema, pero limpiarla le toca a usted.",
  },
};
