import { HelpBody } from './helpContent';

/**
 * The help catalog in Spanish.
 *
 * <p>A file per language: a translation pass is then reviewable on its own, and eighteen articles
 * in five languages inline would be one literal nobody could edit without breaking a quote. A key
 * that is missing here falls back to the English body, visibly — see `bodyFor`.</p>
 */
export const ES: Readonly<Record<string, HelpBody>> = {
  "install-the-server": {
    title: "Empiece aquí: instale el servidor MCP",
    whatItIs: "La extensión es la cara. Quien hace la revisión es `coai-mcp`, un programa pequeño que arranca su asistente de IA. Mientras no esté instalado, no revisa nadie.",
    why: "Una revisión tiene que ejecutarse donde está su código, lanzar las CLI de los proveedores y trabajar durante minutos. Una extensión de VS Code no puede hacerlo, y un servidor propiedad de una ventana de VS Code moriría con ella.",
    setup: "Abra la sección **Server**. Ahí se ve qué hay instalado, qué hay publicado, y un botón cuando difieren: púlselo. La descarga se verifica contra el `.sha256` de la propia release, el binario va al almacén privado de la extensión y no entra en el `PATH`.\n\nDespués, menú ⋯ → **Copy the MCP config block** y pegue el bloque en la configuración de su asistente. Esto se hace UNA vez. Reinicie el asistente para que levante el servidor.",
    usage: "Después volverá poco a la sección Server: la versión publicada se reconsulta como mucho cada media hora, y **Check again** pregunta ahora mismo.\n\nCada plataforma tiene su propio binario. En cada release se publican compilaciones para Windows, macOS y Linux; una máquina sin la suya lo dice con franqueza en vez de descargar la ajena.",
    whatCanGoWrong: "Si el panel dice que no pudo leer la versión publicada, no se alcanzó GitHub. Nada está roto: el servidor instalado funciona.\n\nSi tras pegar el bloque su asistente no muestra las herramientas, no se ha reiniciado. El bloque lleva la ruta exacta al binario; un bloque copiado de otra máquina apunta a una ruta que aquí no existe.",
  },
  "choose-reviewers": {
    title: "Después: elija quién revisa",
    whatItIs: "La sección **Reviewers** es el panel de modelos ajenos que leerá su plan y su código. Cada fila es un proveedor: una casilla para incluirlo, un selector de modelo, un ▶ para abrir su CLI en una terminal, un ⤓ para instalar esa CLI, su precio por millón de tokens y **remove**.",
    why: "Todo el sentido está en que el revisor no es el autor. Una segunda opinión del mismo modelo que escribió el código vale menos que una primera opinión de otro — y dos proveedores que coinciden en un hallazgo son la señal más fuerte que produce este producto.",
    setup: "**＋ Add a reviewer** ofrece los proveedores que conoce esta compilación: Codex, Antigravity (Gemini, Claude y GPT-OSS con una sola suscripción), un segundo Claude, DeepSeek, OpenRouter y una fila en blanco para cualquier endpoint compatible con OpenAI.\n\nLa mayoría se autentican solos: si la CLI está conectada en esta máquina, no hace falta clave. El ▶ de una fila abre una terminal con esa CLI — ahí la conecta, y ahí su propio comando de consumo ya está escrito esperando Enter. El ⤓ abre la misma terminal con el comando de INSTALACIÓN — el oficial del proveedor, para el sistema operativo en el que esa terminal realmente se ejecuta. VS Code conectado a WSL recibe el comando de Linux, no el de PowerShell.",
    usage: "Dos revisores es el mínimo útil, porque la señal es la coincidencia. Tres cuestan el triple y rara vez dicen el triple.\n\nEl selector de modelo muestra a qué llega de verdad esa CLI en esta máquina: en Codex, su propia caché de modelos; en los demás, una lista curada. **another model…** acepta cualquier id exacto.",
    whatCanGoWrong: "Quitar al último revisor se rechaza: un panel sin nadie no revisa nada.\n\nUn proveedor cuya CLI no está instalada lo dice en **providers** antes de una ronda, no a mitad de ella. Gemini está marcado RETIRED: Google cerró Code Assist para cuentas individuales y esa CLI ahora se niega antes de llegar a un modelo. Use Antigravity.",
  },
  "teach-your-ai": {
    title: "Y: dígale a su IA que use la puerta",
    whatItIs: "Menú ⋯ → **Copy the CLAUDE.md snippet** da un párrafo que se pega en el repositorio que quiere revisar. Le dice a la IA que trabaja allí que existe una puerta de revisión y en qué orden se usa.",
    why: "Un asistente con herramientas pero sin instrucción no se le ocurre abrir una sesión de revisión. Ese párrafo ES la instrucción, y vive en el repositorio y no en la extensión porque es una propiedad del proyecto, no de su editor.",
    setup: "Cópielo, péguelo en el `CLAUDE.md` de ese repositorio (o en lo que lea su asistente) y haga commit. No nombra ningún repositorio: la IA que lo lee ya está dentro de una copia de trabajo que puede nombrar ella misma.",
    usage: "A partir de ahí el asistente abre una sesión, envía el plan, resuelve los hallazgos, implementa, envía el diff y vuelve a resolver. Usted lo observa en **Recent rounds** y responde a lo que escale.",
    whatCanGoWrong: "Nada obliga a cumplir ese párrafo. El asistente puede ignorarlo, y la puerta no puede llamarse a sí misma. Lo que SÍ puede es negarse a revisar código mientras el plan no haya pasado, y eso lo hace.",
  },
  "the-gate": {
    title: "La puerta: rondas, el umbral y qué pasa cuando se agotan",
    whatItIs: "Los ajustes que deciden cuándo termina una revisión. **Rounds** es cuántos intentos tiene un ROL. **Passes at or under** es cuántos de sus hallazgos bloqueantes son aceptables. **When the rounds run out** es qué pasa si nunca llega ahí.",
    why: "Sin límite, un bucle de revisión no termina nunca: siempre hay un hallazgo más. El umbral dice con un número qué es «suficiente» antes de que empiece la discusión.",
    setup: "CADA rol tiene sus propias rondas y su propio umbral, y se ajustan junto a los prompts de ese rol: la arquitectura puede merecer dos pasadas con lentes distintas y el rendimiento una, y un presupuesto compartido hace que el rol más barato pague por el más caro. Un hallazgo cuenta contra el umbral DEL rol que lo levantó, así que un rol ruidoso no puede gastarse la tolerancia de otro. Una etapa pasa cuando cada rol está en su número o por debajo, y solo se revisa para los roles que aún tienen rondas.\n\nAl lado está el otro interruptor, **Deal the lenses across vendors**: apagado, cada proveedor responde la misma pregunta y la coincidencia de dos proveedores es un hecho que la puerta puede usar; encendido, cada lente se pregunta una vez, con la mitad de lanzamientos, y esa coincidencia desaparece.\n\nPor omisión: tres rondas de plan con umbral dos, dos rondas por cada rol de código con umbral tres, reparto apagado y la política *Ask a human*. Al umbral solo cuentan los hallazgos **blocking** y **major**; minor y nit nunca bloquean.\n\nUn hallazgo levantado por dos proveedores cuenta UNA vez. Un hallazgo que usted rechazó con motivo no vuelve a contar hasta que un revisor lo levante con un argumento realmente nuevo.",
    usage: "*Ask a human* es la opción honesta por omisión: la puerta se detiene y pone la decisión delante de usted. *Continue anyway* sigue y dice en voz alta que quedan hallazgos — y no toca ninguno, que es exactamente cómo una puerta se vuelve decoración. *Good enough — take what’s true and move on* es la intermedia: la IA lee los hallazgos abiertos, aplica los que son verdaderos y útiles, rechaza el resto con motivos y sigue. *Escalate* sube una escalera — más esfuerzo del revisor, luego un modelo revisor más fuerte, luego un árbitro más fuerte — y da a la etapa un juego nuevo de rondas cada vez.",
    whatCanGoWrong: "Un umbral de cero significa que bloquea cualquier hallazgo de cualquier gravedad, lo que en la práctica significa que una revisión no pasa nunca.\n\nLas rondas son por ETAPA: la puerta del plan y la del código reciben cada una la cuenta completa.",
  },
  "prompts-per-round": {
    title: "Prompts por ronda: qué pregunta hace cada ronda",
    whatItIs: "Cada rol de revisor tiene un prompt universal y dos lentes estrechas. Aquí se elige qué prompt usa cada RONDA de ese rol, y está junto a las rondas y el umbral del mismo rol, porque esos tres ajustes responden juntos a una sola pregunta.",
    why: "Un prompt por rol para siempre es la omisión correcta y el techo equivocado. Cuando se le pide a un modelo mirar todo, se reparte fino, y una segunda ronda de la misma pregunta amplia suele devolver las mismas respuestas amplias.",
    setup: "Un selector por ronda por rol; cada opción lleva su propósito como ayuda. Una ronda que no ha tocado muestra lo que el servidor va a ejecutar de verdad para ella — el selector nunca es una suposición ni un prompt que nadie ejecutará.\n\n**La ronda uno de cada rol de CÓDIGO es la pasada de convenciones, salvo que elija otra cosa.** Juzga el diff contra las reglas que este proyecto ha escrito — nada más — y un hallazgo ahí tiene que citar la frase que rompe. Un repositorio sin archivos de reglas cae al prompt universal de ese rol, porque una pasada de convenciones sin convenciones no tiene nada que decir.\n\nCualquier otra ronda sin fijar es la pregunta universal de ese rol. Una lente se pregunta cuando usted la pregunta: ya no hay rotación automática. Hubo una, no le quedaba ningún interruptor al que el panel llegara, y su único efecto restante era que este selector nombraba un prompt que el servidor no ejecutaría.",
    usage: "**Deal the lenses across vendors** es el interruptor junto a estos selectores, y es el que cambia cómo se gasta una ronda: apagado, cada proveedor responde cada pregunta de esa ronda; encendido, los prompts de la ronda se reparten uno por proveedor, y una ronda cuesta un lanzamiento por proveedor en vez de uno por prompt por proveedor. Lo que gasta es el acuerdo: dos proveedores que presentan el mismo hallazgo son la señal más fuerte de este producto, y una ronda repartida no puede producirla. Por eso está apagado por omisión.\n\nCuando de verdad quiera dos lentes distintas sobre un cambio, póngalas en dos rondas y deje correr las dos. Se midió: en dos rondas de código, gastarlas en lentes distintas encontró MENOS hallazgos distintos que hacer dos veces la pregunta universal (17 contra 25), por menos dinero — por eso nada lo hace por usted.\n\nEl texto completo de cada prompt está en **The prompts, in full**.",
    whatCanGoWrong: "**Lo que la medición NO establece.** En tres planes, la unión de tres lentes encontró aproximadamente el doble que cualquiera sola — y ese resultado no sobrevive a su propio control: el MISMO prompt sobre el MISMO texto tres veces dio 6, 4 y 5 hallazgos con solapamientos de 3, 1 y cero. La varianza entre ejecuciones explica sola esa diferencia. Las lentes se ofrecen porque sirven para apuntar, no porque se haya demostrado que encuentran más.",
  },
  "limits": {
    title: "Límites: cuántos a la vez y cuánto se espera a cada uno",
    whatItIs: "**Reviewers at once** limita todo el abanico. **Per vendor** limita a un proveedor. **Reviewer timeout**: cuánto puede tardar un revisor. **Wait for you**: cuánto espera una escalada a una persona antes de rendirse.",
    why: "Una ronda de código son seis procesos que quieren arrancar en el mismo segundo: tres roles por dos proveedores. Sin límite, es justo aquí donde llegan a la vez los límites de procesos del sistema, los ficheros de bloqueo de las propias CLI y los límites de los proveedores — y cada uno parece un timeout mientras no se le llame por su nombre.",
    setup: "Por defecto, tres a la vez y dos por proveedor. El límite por proveedor existe porque el límite de peticiones se cuenta por proveedor: un único límite global gastaría tranquilamente todas las plazas en uno solo.\n\nEl timeout del revisor es de diez minutos. Una ronda de código sobre un diff grande tarda de tres a cinco.",
    usage: "Suba el límite global en una máquina con núcleos libres y bájelo en el portátil en el que además está trabajando. Quien choque contra los límites del proveedor debe bajar precisamente el límite POR PROVEEDOR.",
    whatCanGoWrong: "El timeout mata todo el árbol de procesos, no solo la CLI: los hijos de un revisor no le sobreviven.\n\nQue expire **Wait for you** no es una negativa: la escalada sigue abierta en el panel, y la IA recibe la instrucción de preguntarle en la conversación.",
  },
  "language-and-translator": {
    title: "Idioma: las preguntas van en inglés",
    whatItIs: "Aquí ya no hay nada que ajustar. Una pregunta `call_human` le llega como una frase fija en inglés y tres botones, y su respuesta vuelve exactamente como la dio.",
    why: "Antes había un traductor: la pregunta era prosa que había escrito una IA, había que leerla y usted respondía con sus palabras. Tres botones quitaron todo eso. Un subproceso por escalada que puede expirar, negarse o responder en el idioma equivocado es una pieza móvil que no gana nada.",
    setup: "Nada. Los controles **Ask and answer in** y **Translated by** ya no están, junto con los ajustes `COAI_LANGUAGE` y `COAI_TRANSLATOR_*` que había detrás.",
    usage: "El idioma de ESTA ayuda es aparte y sigue siendo suyo: el selector de la parte superior de estas páginas lo cambia, y se guarda como `coai.helpLanguage`. Lo que cambió es el lado de los revisores, no el de la lectura.",
    whatCanGoWrong: "Aquí ya no puede fallar nada, que era el punto. Si escribe texto libre en un botón que lo permite, llega a la IA sin mediación — vale más que las mismas palabras pasadas a otro idioma por un tercer modelo.",
  },
  "vendor-keys": {
    title: "Claves de proveedor: solo cuando una CLI no sabe autenticarse sola",
    whatItIs: "Una única entrada de tipo `config` en CredsForDevs que guarda una clave por cada proveedor que la necesite. El panel muestra cuál de sus revisores la necesita de verdad.",
    why: "La mayoría de las CLI de revisor ya tienen sesión iniciada en su máquina y no necesitan clave alguna. Quienes sí la necesitan — un endpoint propio, DeepSeek, OpenRouter — no deberían teclearla en un fichero de ajustes.",
    setup: "Solo hace falta si la fila del revisor lo dice. Cree una entrada `config` en CredsForDevs, guarde ahí las claves como `{\"deepseek\": \"sk-…\"}` y pegue su identificador en **CredsForDevs config key**.",
    usage: "El servidor lee la entrada al arrancar y pasa cada clave a su proveedor por el entorno, nunca por la línea de comandos. Cambiar una clave surte efecto en el siguiente arranque del servidor.",
    whatCanGoWrong: "Un proveedor que necesita clave y no la tiene aparece en **providers** como `unavailable` con su motivo y se cae del abanico — no se salta en silencio.",
  },
  "recent-rounds": {
    title: "Recent rounds: qué hubo y qué está pasando ahora",
    whatItIs: "Las últimas rondas, las recientes arriba, y la que está en curso siempre primera. En la fila: qué se revisó, la etapa, el veredicto, el número de hallazgos bloqueantes, el tiempo y el gasto.",
    why: "Una revisión tarda minutos. Sin esto, el panel no distinguiría «seis revisores trabajando» de «aquí no se ha ejecutado nunca nada», y habría que bajar al log.",
    setup: "Nada que configurar. El servidor escribe la ronda en disco en el momento de arrancarla y la actualiza a medida que avanzan los revisores, así que la imagen sobrevive a recargar la ventana, reiniciar la extensión y matar el servidor.",
    usage: "La ronda en curso muestra sus revisores y qué hace cada uno. **Show review rounds** en el menú ⋯ abre lo mismo como fichero, que puede dejar abierto junto al trabajo: se reescribe según avanzan las rondas.",
    whatCanGoWrong: "Una ronda abandonada por un servidor caído se lee como *interrupted*, no como «lleva ejecutándose para siempre». Las rondas escritas por un servidor antiguo pueden no tener gasto ni tema: entonces no se guardaban, y rellenarlo a posteriori sería inventarlo.",
  },
  "what-each-ai-has-used": {
    title: "Qué ha gastado cada IA: tokens, dinero y tiempo",
    whatItIs: "Una barra por proveedor sobre un día, una semana, un mes o un año: tokens de entrada y salida, **dinero**, cuántas ejecuciones, cuántas fallaron, tiempo total y medio — y una línea al final que suma todos los proveedores.",
    why: "Un panel de revisión gasta dinero real en cada ronda, y la pregunta «cuánto me ha costado este mes» no se responde desde un archivo de sesión: las sesiones se reescriben conforme avanzan las rondas y guardan una rama cada una.",
    setup: "Para los tokens no hay nada que configurar: el servidor añade una línea por revisor a `usage.jsonl` en su directorio de datos, y esta sección la lee.\n\nPara el DINERO hay una cosa, y solo usted puede darla: **cuánto cobra este proveedor por millón de tokens, de entrada y de salida**, en su propia fila. Este producto no incluye tabla de precios a propósito — una incluida está mal para quien tenga una suscripción plana, mal en cuanto un proveedor cambie un precio, y mal en silencio en ambos casos. Ponga una tarifa y aparece el dinero de ese proveedor; déjela vacía y queda un guion.",
    usage: "**Un revisor que falla también se cuenta.** Una ejecución que quemó noventa segundos y no respondió nada es justo lo que un registro de gasto no debe esconder, así que cada fila lleva su resultado y el número de fallos va junto a los tokens.\n\n**La tilde carga significado.** `$0.42` es lo que cobró un proveedor; `~$0.42` es lo que sale de su propia tarifa. Claude informa su coste, Codex y Antigravity informan solo tokens — así que en esos dos hay tilde o guion, nunca una cifra desnuda. El total mantiene las mitades separadas por lo mismo: se lee `$0.18 + ~$0.31` en vez de sumar un hecho con un cálculo y presentar el resultado como uno de los dos.\n\nPor debajo de un dólar el dinero se muestra con cuatro decimales. Una ronda que costó ocho centésimas de centavo es un número real, y redondearlo a `$0.00` dice que el panel no está contando.",
    whatCanGoWrong: "Los tokens se cuentan por proveedor porque una sola regla sería falsa para al menos uno: Codex mete los tokens en caché DENTRO de la entrada, Claude los informa AL LADO, y en Antigravity los tokens de razonamiento van dentro de la salida. Claude además informa la misma ejecución dos veces con números distintos; se usa el agregado.",
  },
  "questions-waiting": {
    title: "Una pregunta que le espera",
    whatItIs: "Cuando la puerta necesita a una persona, arriba del panel aparece una tarjeta con la pregunta y los hallazgos que siguen bloqueando. Se abre un diálogo, aparece un elemento en la barra de estado y el icono del título se pone verde.",
    why: "Detrás de esa pregunta hay una ronda BLOQUEADA. Una notificación que se puede perder no sirve para esto — de ahí las tres superficies, y cerrar el diálogo no pierde nada.",
    setup: "Nada que configurar. El servidor escribe la pregunta como fichero en el directorio que la extensión ya vigila: ninguna de las dos mitades abre un puerto.",
    usage: "Puede responder en el panel, en el diálogo o desde la barra de estado: es la misma acción. La respuesta va a la IA que preguntó, traducida al idioma en que preguntó, y sus propias palabras se conservan al lado.",
    whatCanGoWrong: "El veredicto `call_human` también levanta una tarjeta así, de modo que una puerta con las rondas agotadas le alcanza aunque la IA calle. No siempre fue así: antes el veredicto era una instrucción solo para la IA, y una persona podía mirar el panel todo el día sin enterarse de que la habían llamado.",
  },
  "prompts-in-full": {
    title: "Los prompts, completos",
    whatItIs: "El texto completo de cada prompt que este producto envía a un revisor — los cuatro universales, las ocho lentes estrechas y la pasada de convenciones. Aquí no hay nada parafraseado; esto es lo que lee el modelo.",
    why: "Una revisión que no se puede auditar es una revisión que hay que creer. Saber exactamente qué se preguntó es lo que permite juzgar si una respuesta fue justa — y si un hallazgo con el que no está de acuerdo vino de un modelo malo o de una pregunta mala.",
    setup: "Nada que configurar. Lo impreso abajo se compara con los propios archivos de prompts del servidor mediante un test, así que no puede desviarse de lo que realmente se ejecuta.\n\nEl prompt **conventions** va aparte y no bajo un rol, porque no es una lente sobre la pregunta de un rol: es otra pregunta que los tres roles de código hacen en la ronda uno. Las reglas llegan con él — los propios `CLAUDE.md`, `AGENTS.md`, `GEMINI.md` y `.claude/rules` del proyecto, leídos del worktree del commit revisado y citados literalmente, hasta 40 KB, y lo que quede fuera se nombra en vez de descartarse en silencio.",
    usage: "Cada prompt termina con la misma disciplina: un hallazgo debe nombrar una situación concreta y el resultado equivocado que produce; cuatro clases de no-hallazgo están nombradas y prohibidas; y se dice expresamente que una lista de hallazgos vacía es una respuesta válida — a un revisor al que se le dice que siempre encuentre algo, siempre encontrará algo.\n\nPuede sobrescribir cualquiera: deje un archivo con el nombre del prompt en `prompts/` dentro del directorio de datos del servidor y gana mientras exista. Bórrelo y vuelve el texto de fábrica.",
    whatCanGoWrong: "Una sobrescritura no se valida. Un prompt que no pide el esquema de hallazgos producirá respuestas que no se pueden parsear, y la ronda informará de ese revisor como no parseable — guardando su respuesta cruda en disco para que vea qué pidió.",
  },
  "the-help-page": {
    title: "Esta página: búsqueda, idioma y tamaño del texto",
    whatItIs: "El ? amarillo del título del panel abre esta ayuda. La lista muestra cada artículo con su primera línea; el campo de arriba busca en todos; el desplegable cambia el idioma; los botones ± cambian el tamaño del texto.",
    why: "Un panel de ajustes con dieciséis elementos necesita un sitio donde se diga qué hace cada uno — un tooltip no sirve. El tamaño del texto está aquí porque la vista no es materia de discusión: cinco pasos en cada sentido son aproximadamente ×1,6 arriba o abajo.",
    setup: "Nada que configurar. El selector de idioma escribe `coai.helpLanguage` y solo afecta a estas páginas — no es el idioma en el que se pregunta a sus revisores, ese está en la sección **Language**. Los botones ± escriben `coai.uiScale`. Ambos son ajustes reales, así que se sincronizan con sus otras máquinas.",
    usage: "La búsqueda recorre los títulos Y el texto completo de cada artículo en el idioma mostrado, así que una palabra que recuerde de un párrafo encuentra el artículo donde estaba. Escape cierra un artículo y vuelve a la lista, y Back conserva lo escrito.\n\nUn artículo sin traducir muestra el inglés con una nota visible, no una página en blanco.",
    whatCanGoWrong: "Que una traducción vaya por detrás del inglés es normal y se señala. Lo que no puede pasar es que falte un artículo: un test de cobertura tumba la compilación cuando de un comando o un ajuste no hay nada escrito. Justo por eso esta página no puede convertirse en silencio en la descripción de un producto que ya no existe.",
  },
  "the-protocol": {
    title: "Bajo el capó: el protocolo que sigue su IA",
    whatItIs: "Siete herramientas en orden estricto. `open` abre una sesión para un repositorio y una rama. `review_plan` envía el plan a todos los revisores. `resolve` registra la aceptación o el rechazo de CADA hallazgo. `review_code` hace lo mismo con el diff, con tres roles por proveedor. `providers` muestra el estado, `status` devuelve al contexto una conversación reanudada, y `ask_human` escala hasta usted.",
    why: "El orden se sostiene por rechazo, no por buena conducta: `review_code` se niega mientras ninguna ronda de plan haya llegado a *proceed*, de modo que saltarse una etapa es imposible, no «desaconsejable».",
    setup: "Nada que configurar: esto lo maneja su IA. El orden se lo dice justo el fragmento que usted pegó en el repositorio.",
    usage: "Un rechazo exige un motivo, y el motivo se conserva: un hallazgo rechazado no cuenta en las siguientes rondas hasta que un revisor lo vuelva a plantear con un argumento nuevo. Eso es lo que impide que el bucle reabra una decisión que usted ya tomó.",
    whatCanGoWrong: "Una ronda en la que no respondió NADIE no pasa nunca. Un resultado vacío es ausencia de evidencia, no evidencia de ausencia: la puerta llama a una persona en su lugar. Es el único caso en el que «sin hallazgos» no debe significar «aprobado».",
  },
  "where-reviewers-run": {
    title: "Bajo el capó: dónde se ejecuta realmente un revisor",
    whatItIs: "La etapa de código da a la ronda UN git-worktree, fijado al commit de la rama, solo lectura. La etapa de plan da en cambio a cada revisor un directorio VACÍO.",
    why: "Si a una CLI agéntica se le da un repositorio y un plan que menciona ficheros, va a leerlos. Medido: ocho minutos y aún ejecutándose — sobre un documento de quince kilobytes. Ahí el papel es juzgar el DOCUMENTO; el repositorio lo necesita la etapa de código.",
    setup: "Nada que configurar. Los worktrees viven en el directorio de datos del servidor y se limpian al abrir una sesión, así que una ronda abortada no deja nada detrás.",
    usage: "Lo que cuesta el directorio vacío, sin rodeos: un revisor de plan no puede comprobar que una referencia del tipo `file.cs:line` sea real. Esa comprobación nunca estuvo en el prompt del plan, y comprarla al precio de diez veces el tiempo es el cambio equivocado para una puerta en la que hay una persona esperando.",
    whatCanGoWrong: "El único reintento de un revisor también se ejecuta en un directorio vacío, por la misma razón: la reparación pide la respuesta con el esquema, no una investigación nueva. Precisamente volver a entregarle un checkout costaba un revisor en una de cada tres rondas de código.",
  },
  "when-a-reviewer-fails": {
    title: "Bajo el capó: qué pasa cuando un revisor falla",
    whatItIs: "Seis desenlaces con nombre, y nunca un cero silencioso: respondió, agotó el tiempo, terminó con código distinto de cero, chocó con un límite, no pudo arrancar, o respondió algo que no se puede parsear. Una ronda que pasó con cuatro revisores de seis lo dice así, con nombres.",
    why: "Un panel que no revisó no es un panel que aprobó. Cada ronda incompleta se informa como incompleta, y la frase sobre los revisores nombra quién falló y por qué.",
    setup: "Nada que configurar. Un revisor con límite de peticiones se reintenta una sola vez tras una pausa — salvo que el proveedor haya dicho que el límite es DIARIO, y eso no lo cura ningún reintento.",
    usage: "Una negativa lleva las propias palabras de la CLI, elegidas por contenido y no por posición: la primera línea que anuncia un error, saltándose los marcos de pila y los banners de versión. Para cinco negativas conocidas — CLI cerrada, directorio no confiable, binario ausente para la plataforma — se dice QUÉ HACER, no qué se imprimió.",
    whatCanGoWrong: "Una respuesta que no se pudo parsear se guarda en disco bajo `unparseable/` dentro del directorio de datos, y la negativa nombra el fichero. Esto nació porque esa misma respuesta, reproducida a mano, pasaba sin problemas: el mensaje nombraba un síntoma imposible de investigar.",
  },
  "settings-and-the-server": {
    title: "Bajo el capó: cómo llega un ajuste al servidor",
    whatItIs: "El panel escribe sus ajustes en un fichero dentro del directorio de datos del servidor, y el servidor relee ese fichero cada vez que cambia.",
    why: "Antes los ajustes llegaban al servidor solo dentro del bloque de configuración pegado, y cambiar un umbral se convertía en un trámite: copiar el bloque, encontrar la configuración del cliente, pegar, reiniciar. Y solo se aplicaban al arrancar — una brecha invisible desde ambos lados, porque el panel guarda al instante y así lo dice.",
    setup: "Nada que configurar. Un cambio en el panel rige desde la SIGUIENTE ronda: ni reinicio ni volver a pegar.",
    usage: "Una variable puesta en la configuración del propio asistente sigue ganando al fichero: es más específica que un fichero que cualquier ventana puede reescribir.\n\nEl panel escribe solo lo que DIFIERE de los valores por defecto, así que devolver un ajuste a su valor por defecto lo quita del fichero en vez de fijarlo.",
    whatCanGoWrong: "Un fichero a medio escribir deja en pie la última configuración que funcionaba. Una lectura rota que diera una lista de proveedores vacía habría hecho fallar a todos los revisores y lo habría informado un panel de acuerdo consigo mismo.",
  },
  "the-audit-log": {
    title: "Bajo el capó: el registro de auditoría",
    whatItIs: "Un fichero de log por arranque del servidor, junto al binario instalado, en `logs/<día>/`. Contiene el reparto de cada ronda, el arranque y la respuesta de cada revisor con tokens y dinero, cada negativa como aviso con su motivo, y cada hallazgo con su procedencia.",
    why: "El resumen de una ronda es deliberadamente una frase, y una frase no responde a «por qué falló ese revisor». Esa pregunta surgió dos veces en una puerta real, y las dos veces no había nada que responder.",
    setup: "Nada que configurar. Los niveles vienen de la configuración y no de los puntos de llamada, y cada arranque escribe un fichero nuevo — no uno por día, porque casi siempre se pregunta qué hizo AQUELLA ejecución.",
    usage: "En nivel debug se escribe la línea de comandos exacta de cada revisor: esa es la diferencia entre «saber que se preguntó al proveedor» y «pegar el comando en una terminal y ver la misma negativa».",
    whatCanGoWrong: "El log es el único sitio donde algunas cosas quedan registradas. No rota ni se recorta: un año de trabajo denso es una carpeta de ficheros pequeños — no es un problema, pero limpiarla le toca a usted.",
  },
};
