import { HelpBody } from './helpContent';

/**
 * The help catalog in German.
 *
 * <p>A file per language: a translation pass is then reviewable on its own, and eighteen articles
 * in five languages inline would be one literal nobody could edit without breaking a quote. A key
 * that is missing here falls back to the English body, visibly — see `bodyFor`.</p>
 */
export const DE: Readonly<Record<string, HelpBody>> = {
  "install-the-server": {
    title: "Hier anfangen: den MCP-Server installieren",
    whatItIs: "Die Erweiterung ist das Gesicht. Das Review macht `coai-mcp`, ein kleines Programm, das Ihr KI-Assistent startet. Solange es nicht installiert ist, reviewt niemand.",
    why: "Ein Review muss dort laufen, wo Ihr Code liegt, Hersteller-CLIs starten und minutenlang arbeiten. Das kann eine VS-Code-Erweiterung nicht, und ein Server, der einem VS-Code-Fenster gehörte, würde mit ihm sterben.",
    setup: "Öffnen Sie den Abschnitt **Server**. Dort steht, was installiert und was veröffentlicht ist, und eine Schaltfläche, wenn beides auseinandergeht — drücken Sie sie. Der Download wird gegen die `.sha256` des Releases geprüft, die Binärdatei landet im privaten Speicher der Erweiterung und kommt nicht in den `PATH`.\n\nDann Menü ⋯ → **Copy the MCP config block** und den Block in die Konfiguration Ihres Assistenten einfügen. Das passiert EINMAL. Starten Sie den Assistenten neu, damit er den Server hochfährt.",
    usage: "Danach kommen Sie selten in den Server-Abschnitt zurück: die veröffentlichte Version wird höchstens halbstündlich neu abgefragt, **Check again** fragt sofort.\n\nJede Plattform hat ihre eigene Binärdatei. Zu jedem Release erscheinen Builds für Windows, macOS und Linux; eine Maschine ohne eigenen Build sagt das ehrlich, statt einen fremden zu laden.",
    whatCanGoWrong: "Steht im Panel, die veröffentlichte Version sei nicht lesbar, wurde GitHub nicht erreicht. Nichts ist kaputt, der installierte Server läuft.\n\nZeigt Ihr Assistent nach dem Einfügen keine Werkzeuge, wurde er nicht neu gestartet. Im Block steht der exakte Pfad zur Binärdatei; ein von einer anderen Maschine kopierter Block zeigt auf einen Pfad, den es hier nicht gibt.",
  },
  "choose-reviewers": {
    title: "Dann: wählen, wer reviewt",
    whatItIs: "Der Abschnitt **Reviewers** ist die Besetzung fremder Modelle, die Ihren Plan und Ihren Code lesen. Jede Zeile ist ein Hersteller: ein Schalter, eine Modellwahl, ▶ zum Öffnen seiner CLI im Terminal und **remove**.",
    why: "Der ganze Sinn ist, dass der Reviewer nicht der Autor ist. Die zweite Meinung desselben Modells, das den Code geschrieben hat, ist weniger wert als die erste Meinung eines anderen. Und ein Befund, bei dem zwei Hersteller übereinstimmen, ist das stärkste Signal, das dieses Produkt überhaupt liefert.",
    setup: "**＋ Add a reviewer** bietet die Hersteller an, die dieser Build kennt: Codex, Antigravity (Gemini, Claude und GPT-OSS über ein Abo), einen zweiten Claude, DeepSeek, OpenRouter und eine leere Zeile für jeden OpenAI-kompatiblen Endpunkt.\n\nDie meisten melden sich selbst an: ist die CLI auf dieser Maschine angemeldet, braucht es keinen Schlüssel. Die Schaltfläche ▶ öffnet ein Terminal mit dieser CLI — dort melden Sie sie an, und dort steht ihr Verbrauchsbefehl bereits getippt, es fehlt nur die Eingabetaste.",
    usage: "Zwei Reviewer sind das sinnvolle Minimum, weil die Übereinstimmung das Signal ist. Drei kosten das Dreifache und sagen selten dreimal so viel.\n\nDie Modellwahl zeigt, was diese CLI auf dieser Maschine tatsächlich erreicht: bei Codex ihr eigener Modell-Cache, sonst eine gepflegte Liste. **another model…** nimmt jede exakte ID.",
    whatCanGoWrong: "Den letzten Reviewer können Sie nicht entfernen: ein Panel ohne Teilnehmer reviewt nichts.\n\nEin Hersteller, dessen CLI fehlt, sagt das in **providers** VOR der Runde, nicht mitten darin. Gesondert zu Gemini: es ist als RETIRED markiert — Google hat Code Assist für Einzelkonten geschlossen, und diese CLI verweigert nun, bevor sie ein Modell erreicht. Nehmen Sie Antigravity.",
  },
  "teach-your-ai": {
    title: "Und: Ihrer KI sagen, das Gate zu benutzen",
    whatItIs: "Menü ⋯ → **Copy the CLAUDE.md snippet** liefert einen Absatz, der in das Repository kommt, das Sie reviewen lassen wollen. Er sagt der dort arbeitenden KI, dass es ein Review-Gate gibt und in welcher Reihenfolge es benutzt wird.",
    why: "Ein Assistent mit Werkzeugen, aber ohne Anweisung, kommt nicht von selbst darauf, eine Review-Sitzung zu öffnen. Dieser Absatz IST die Anweisung, und er lebt im Repository statt in der Erweiterung, weil er eine Eigenschaft des Projekts ist und nicht Ihres Editors.",
    setup: "Kopieren, in die `CLAUDE.md` jenes Repositories einfügen (oder in das, was Ihr Assistent liest), committen. Er nennt kein Repository: die KI, die ihn liest, sitzt ohnehin in einer Arbeitskopie, die sie selbst benennen kann.",
    usage: "Danach öffnet der Assistent eine Sitzung, schickt den Plan, arbeitet die Befunde ab, implementiert, schickt das Diff und arbeitet erneut ab. Sie sehen das unter **Recent rounds** und beantworten, was er eskaliert.",
    whatCanGoWrong: "Nichts erzwingt diesen Absatz. Der Assistent kann ihn ignorieren, und das Gate kann sich nicht selbst aufrufen. Was es KANN: sich weigern, Code zu reviewen, solange der Plan nicht durch ist — und das tut es.",
  },
  "the-gate": {
    title: "Das Gate: Runden, Schwelle und was passiert, wenn sie aufgebraucht sind",
    whatItIs: "Drei Einstellungen entscheiden, wann ein Review fertig ist. **Rounds per stage** — wie viele Versuche eine Stufe bekommt. **Passes at or under** — wie viele blockierende Befunde zulässig sind. **When the rounds run out** — was geschieht, wenn es nicht gereicht hat.",
    why: "Ohne Grenze endet die Review-Schleife nie: ein weiterer Befund findet sich immer. Die Schwelle beziffert vor dem Streit, was „genug“ heißt.",
    setup: "Voreinstellung: drei Runden, Schwelle zwei, *Ask a human*. Zur Schwelle zählen nur **blocking** und **major**; minor und nit blockieren nie.\n\nEin Befund, den zwei Hersteller melden, zählt EINMAL. Ein Befund, den Sie mit Begründung abgelehnt haben, zählt nicht mehr, bis ein Reviewer ihn mit einem neuen Argument erneut vorbringt.",
    usage: "*Ask a human* ist die ehrliche Voreinstellung: das Gate hält an und legt Ihnen die Entscheidung vor. *Continue anyway* geht weiter und sagt laut, dass Befunde offen blieben. *Escalate* steigt die Leiter hoch — mehr Reviewer-Aufwand, dann ein stärkeres Reviewer-Modell, dann ein stärkerer Schiedsrichter — und gibt der Stufe jedes Mal einen frischen Satz Runden.",
    whatCanGoWrong: "Schwelle null heißt, dass jeder Befund jeden Schweregrads blockiert — das Review geht also nie durch.\n\nRunden zählen PRO STUFE: Plan und Code haben je einen vollen Satz.",
  },
  "prompts-per-round": {
    title: "Prompts pro Runde und automatischer Wechsel",
    whatItIs: "Jede Reviewer-Rolle hat einen universellen Prompt und zwei enge Linsen. Dieser Abschnitt wählt, welchen Prompt jede RUNDE benutzt, je Rolle — oder lässt die Runden sie automatisch durchlaufen.",
    why: "Ein Prompt pro Rolle für immer ist die richtige Voreinstellung und die falsche Decke. Wird ein Modell gebeten, auf alles zu achten, verteilt es sich, und eine zweite Runde derselben breiten Frage liefert meist dieselben breiten Antworten.",
    setup: "Eine Wahl pro Runde je Rolle; der Zweck jeder Variante steht im Tooltip. **Rotate the lenses automatically** gibt die erste Runde der universellen Frage und jede weitere einer anderen Linse. Eine ausdrückliche Wahl schlägt die Rotation immer.\n\nEine Runde, die Sie nicht angefasst haben, bleibt ungesetzt, und die Rotation gilt für sie weiter.",
    usage: "Die Rotation ist standardmäßig AUS, und das ist eine Entscheidung, keine Vorsicht. Gemessen gegen den universellen Prompt über zwei Code-Runden lieferte sie WENIGER verschiedene Befunde (17 statt 25), für weniger Geld.\n\nDie vollständigen Prompt-Texte stehen im Artikel **Prompts im Wortlaut**.",
    whatCanGoWrong: "**Was die Messung nicht beweist.** Über drei Pläne fand die Vereinigung der drei Linsen etwa doppelt so viel wie jede einzelne — und dieses Ergebnis überlebte die eigene Kontrolle nicht: derselbe Prompt auf demselben Text ergab dreimal 6, 4 und 5 Befunde, mit Überschneidungen von 3, 1 und null. Die Streuung des Modells erklärt alles allein. Die Linsen sind ein Weg zu zielen, kein bewiesener Weg, mehr zu finden.",
  },
  "limits": {
    title: "Grenzen: wie viele gleichzeitig und wie lange auf jeden gewartet wird",
    whatItIs: "**Reviewers at once** begrenzt den ganzen Fächer. **Per vendor** begrenzt einen Hersteller. **Reviewer timeout** — wie lange ein Reviewer laufen darf. **Wait for you** — wie lange eine Eskalation auf einen Menschen wartet, bevor sie aufgibt.",
    why: "Eine Code-Runde sind sechs Prozesse, die in derselben Sekunde starten wollen: drei Rollen mal zwei Hersteller. Ohne Grenze treffen genau hier Prozesslimits des Systems, die Lock-Dateien der CLIs und die Herstellerlimits gleichzeitig ein — und jedes sieht aus wie ein Timeout, solange es nicht beim Namen genannt wird.",
    setup: "Voreinstellung: drei gleichzeitig, zwei je Hersteller. Die Grenze je Hersteller existiert, weil ein Ratenlimit pro Hersteller gilt: eine einzige gemeinsame Grenze würde alle Plätze bereitwillig an einen vergeben.\n\nDas Reviewer-Timeout sind zehn Minuten. Eine Code-Runde auf einem großen Diff braucht drei bis fünf.",
    usage: "Erhöhen Sie die gemeinsame Grenze auf einer Maschine mit freien Kernen und senken Sie sie auf dem Notebook, auf dem Sie nebenher arbeiten. Wer in Herstellerlimits läuft, senkt die Grenze JE HERSTELLER.",
    whatCanGoWrong: "Das Timeout tötet den ganzen Prozessbaum, nicht nur die CLI: die Kindprozesse eines Reviewers überleben ihn nicht.\n\nDas Ablaufen von **Wait for you** ist keine Absage: die Eskalation bleibt im Panel offen, und die KI wird angewiesen, Sie im Gespräch zu fragen.",
  },
  "language-and-translator": {
    title: "Sprache: die, in der man Sie fragt",
    whatItIs: "**Ask and answer in** ist die Sprache, in der die Frage bei Ihnen ankommt, und die Sprache, AUS der Ihre Antwort zurückübersetzt wird. **Translated by** bestimmt, welches kleine, schnelle Modell das tut.",
    why: "Die fragende KI schreibt meist Englisch. Sie sollten das nicht lesen müssen, und sie sollte Ihre Antwort nicht in einer anderen Sprache auseinandernehmen müssen, um danach zu handeln.",
    setup: "Wählen Sie Ihre Sprache. Der Übersetzer ist voreingestellt ein schnelles Modell, weil es eine Ein-Satz-Aufgabe erledigt, während Sie warten. **Nobody — always show the original** schaltet die Übersetzung ab.",
    usage: "Übersetzt wird in beide Richtungen: die Frage in Ihre Sprache, Ihre Antwort zurück in die Sprache, in der gefragt wurde. Ihre eigenen Worte bleiben immer neben der Übersetzung stehen, also geht darin nichts verloren.",
    whatCanGoWrong: "Ein Übersetzer, der nicht starten konnte, zeigt das Original mit einem Hinweis, nicht Leere. Eine Frage in der falschen Sprache ist lästig; eine verschwundene Frage hält das Review an.",
  },
  "vendor-keys": {
    title: "Hersteller-Schlüssel: nur, wenn eine CLI sich nicht selbst anmelden kann",
    whatItIs: "Ein einzelner `config`-Eintrag in CredsForDevs, der je einen Schlüssel für jeden Hersteller hält, der einen braucht. Das Panel zeigt, welcher Ihrer Reviewer ihn wirklich benötigt.",
    why: "Die meisten Reviewer-CLIs sind auf Ihrer Maschine bereits angemeldet und brauchen gar keinen Schlüssel. Wer einen braucht — ein eigener Endpunkt, DeepSeek, OpenRouter — sollte ihn nicht in eine Einstellungsdatei tippen.",
    setup: "Nur nötig, wenn die Reviewer-Zeile es sagt. Legen Sie in CredsForDevs einen `config`-Eintrag an, hinterlegen Sie die Schlüssel als `{\"deepseek\": \"sk-…\"}` und tragen Sie dessen Kennung unter **CredsForDevs config key** ein.",
    usage: "Der Server liest den Eintrag beim Start und reicht jeden Schlüssel über die Umgebung an seinen Hersteller weiter, nie über die Kommandozeile. Ein gewechselter Schlüssel gilt ab dem nächsten Serverstart.",
    whatCanGoWrong: "Ein Hersteller, der einen Schlüssel braucht und keinen hat, erscheint in **providers** als `unavailable` mit Grund und fällt aus dem Fächer — er wird nicht stillschweigend übersprungen.",
  },
  "recent-rounds": {
    title: "Recent rounds: was war und was gerade läuft",
    whatItIs: "Die letzten Runden, neueste oben, die laufende immer zuerst. In der Zeile: was reviewt wurde, die Stufe, das Verdikt, die Zahl blockierender Befunde, Dauer und Kosten.",
    why: "Ein Review dauert Minuten. Ohne das könnte das Panel „sechs Reviewer arbeiten“ nicht von „hier lief nie etwas“ unterscheiden, und man müsste ins Log steigen.",
    setup: "Nichts einzustellen. Der Server schreibt eine Runde beim Start auf die Platte und aktualisiert sie, während die Reviewer vorankommen — das Bild überlebt also ein neu geladenes Fenster, einen Neustart der Erweiterung und einen abgeschossenen Server.",
    usage: "Die laufende Runde zeigt ihre Reviewer und was jeder tut. **Show review rounds** im ⋯-Menü öffnet dasselbe als Datei, die Sie neben der Arbeit offen lassen können — sie schreibt sich fort, während die Runden laufen.",
    whatCanGoWrong: "Eine Runde, die ein abgestürzter Server zurückließ, liest sich als *interrupted*, nicht als „läuft ewig“. Runden, die ein älterer Server schrieb, haben womöglich weder Kosten noch Thema: das wurde damals nicht geschrieben, und es nachträglich zu ergänzen wäre erfunden.",
  },
  "what-each-ai-has-used": {
    title: "What each AI has used: Tokens, Geld und Zeit",
    whatItIs: "Ein Balken je Hersteller für Tag, Woche, Monat oder Jahr: Tokens ein und aus, Geld, Anzahl der Läufe, wie viele scheiterten, Gesamt- und Durchschnittsdauer, dazu die Summe über alle.",
    why: "Ein Review-Panel gibt in jeder Runde echtes Geld aus, und die Frage „was hat das diesen Monat gekostet“ beantwortet keine Sitzungsdatei: Sitzungen werden während der Runden überschrieben und halten je einen Branch.",
    setup: "Nichts einzustellen. Der Server hängt je Reviewer eine Zeile an `usage.jsonl` in seinem Datenverzeichnis an, und dieser Abschnitt liest sie.",
    usage: "**Ein gescheiterter Reviewer zählt mit.** Ein Lauf, der neunzig Sekunden verbrannte und nichts antwortete, ist genau das, was eine Ausgabenaufzeichnung nicht verstecken darf; darum hat jede Zeile ein Ergebnis, und die Zahl der Fehlschläge steht neben den Tokens.\n\nBeim Geld steht ein Strich, wo ein Hersteller sich selbst nicht bepreist: „kostenlos“ und „nicht gemeldet“ sind verschiedene Tatsachen, und nur eine davon ist eine gute Nachricht. Geld meldet Claude; Codex und Antigravity melden nur Tokens.",
    whatCanGoWrong: "Tokens werden nach den Regeln jedes Herstellers gezählt, weil eine einzige gemeinsame Regel für mindestens einen falsch wäre: bei Codex steckt der Cache IN den Eingabe-Tokens, bei Claude kommt er hinzu, und bei Antigravity liegen die Denk-Tokens innerhalb der Ausgabe. Claude meldet denselben Lauf zusätzlich zweimal und unterschiedlich; genommen wird das Aggregat.",
  },
  "questions-waiting": {
    title: "Eine Frage, die auf Sie wartet",
    whatItIs: "Braucht das Gate einen Menschen, erscheint oben im Panel eine Karte mit der Frage und den weiterhin blockierenden Befunden. Ein Dialog öffnet sich, in der Statusleiste erscheint ein Eintrag, und das Symbol in der Titelzeile wird grün.",
    why: "Hinter dieser Frage steht eine BLOCKIERTE Runde. Eine Benachrichtigung, die man verpassen kann, taugt dafür nicht — daher drei Oberflächen, und das Schließen des Dialogs verliert nichts.",
    setup: "Nichts einzustellen. Der Server schreibt die Frage als Datei in das Verzeichnis, das die Erweiterung ohnehin beobachtet: keine der beiden Hälften öffnet einen Port.",
    usage: "Antworten können Sie im Panel, im Dialog oder aus der Statusleiste — es ist dieselbe Handlung. Die Antwort geht an die fragende KI, übersetzt in die Sprache, in der sie gefragt hat, und Ihre eigenen Worte bleiben daneben stehen.",
    whatCanGoWrong: "Auch das Verdikt `call_human` erzeugt so eine Karte, damit ein Gate mit aufgebrauchten Runden Sie erreicht, selbst wenn die KI schweigt. Das war nicht immer so: früher war das Verdikt nur eine Anweisung an die KI, und ein Mensch konnte den ganzen Tag auf das Panel sehen, ohne zu erfahren, dass er gerufen wurde.",
  },
  "prompts-in-full": {
    title: "Prompts im Wortlaut",
    whatItIs: "Der vollständige Text jedes Prompts, den das Produkt an einen Reviewer schickt — vier universelle und acht enge Linsen. Hier wird nichts nacherzählt: das ist, was das Modell liest.",
    why: "Ein Review, das man nicht prüfen kann, muss man glauben. Die genaue Fragestellung zu kennen ist das Einzige, was erlaubt zu beurteilen, ob eine Antwort fair ist — und ob ein Befund, dem Sie widersprechen, von einem schlechten Modell oder von einer schlechten Frage kommt.",
    setup: "Nichts einzustellen. Was unten steht, wird von einem Test gegen die Prompt-Dateien des Servers geprüft und kann daher nicht von dem abweichen, was tatsächlich läuft.",
    usage: "Jeder Prompt endet mit derselben Disziplin: ein Befund muss eine konkrete Situation und ein falsches Ergebnis nennen, vier Arten von Nicht-Befunden sind benannt und verboten, und die leere Liste ist ausdrücklich eine zulässige Antwort — ein Reviewer, der immer etwas finden soll, findet immer etwas.\n\nJeder lässt sich überschreiben: legen Sie eine Datei mit dem Namen des Prompts in das Verzeichnis `prompts/` im Datenverzeichnis des Servers, und sie gilt, solange sie existiert. Löschen Sie sie, kehrt der reguläre Text zurück.",
    whatCanGoWrong: "Eine Überschreibung wird nicht geprüft. Ein Prompt, der das Befundschema nicht verlangt, liefert Antworten, die niemand parsen kann, und die Runde meldet diesen Reviewer als unlesbar — samt seiner Rohantwort auf der Platte, damit Sie sehen, wonach genau gefragt wurde.",
  },
  "the-help-page": {
    title: "Diese Seite: Suche, Sprache und Textgröße",
    whatItIs: "Das gelbe ? in der Titelzeile öffnet diese Hilfe. Die Liste zeigt jeden Artikel mit seiner ersten Zeile; das Feld oben durchsucht alle; die Auswahl wechselt die Sprache; die ±-Schaltflächen ändern die Textgröße.",
    why: "Ein Einstellungspanel mit sechzehn Elementen braucht einen Ort, der sagt, was jedes tut — ein Tooltip taugt dafür nicht. Die Textgröße steht hier, weil Sehkraft nichts ist, worüber man streitet: fünf Schritte in jede Richtung sind etwa ×1,6 hinauf oder hinunter.",
    setup: "Nichts einzustellen. Der Sprachschalter schreibt `coai.helpLanguage` und gilt nur für diese Seiten — es ist nicht die Sprache, in der Ihre Reviewer gefragt werden, die steht im Abschnitt **Language**. Die ±-Schaltflächen schreiben `coai.uiScale`. Beides sind echte Einstellungen und werden auf Ihre anderen Maschinen synchronisiert.",
    usage: "Gesucht wird in den Überschriften UND im vollen Text jedes Artikels in der gezeigten Sprache — ein Wort, das Ihnen aus einem Absatz in Erinnerung blieb, findet also den Artikel, in dem es stand. Escape schließt einen Artikel zurück zur Liste, und Back behält das Getippte.\n\nEin nicht übersetzter Artikel zeigt Englisch mit sichtbarem Hinweis, keine leere Seite.",
    whatCanGoWrong: "Dass eine Übersetzung dem Englischen hinterherhinkt, ist normal und wird gekennzeichnet. Was nicht passieren kann, ist ein fehlender Artikel: ein Abdeckungstest lässt den Build scheitern, wenn zu einem Befehl oder einer Einstellung nichts geschrieben steht. Genau deshalb kann diese Seite nicht still zur Beschreibung eines Produkts werden, das es nicht mehr gibt.",
  },
  "the-protocol": {
    title: "Unter der Haube: das Protokoll, dem Ihre KI folgt",
    whatItIs: "Sieben Werkzeuge in fester Reihenfolge. `open` öffnet eine Sitzung für Repository und Branch. `review_plan` schickt den Plan an alle Reviewer. `resolve` hält für JEDEN Befund fest, ob er angenommen oder abgelehnt wurde. `review_code` tut dasselbe für das Diff, mit drei Rollen je Hersteller. `providers` zeigt den Zustand, `status` bringt ein wieder aufgenommenes Gespräch zurück in den Kontext, `ask_human` eskaliert zu Ihnen.",
    why: "Die Reihenfolge hält durch Verweigerung, nicht durch gutes Benehmen: `review_code` verweigert, solange keine Planrunde *proceed* erreicht hat — eine Stufe zu überspringen ist also unmöglich und nicht bloß „nicht empfohlen“.",
    setup: "Nichts einzustellen — das steuert Ihre KI. Die Reihenfolge sagt ihr genau der Absatz, den Sie ins Repository eingefügt haben.",
    usage: "Eine Ablehnung verlangt eine Begründung, und die Begründung bleibt erhalten: ein abgelehnter Befund zählt in weiteren Runden nicht, bis ein Reviewer ihn mit einem neuen Argument erneut vorbringt. Genau das hindert die Schleife daran, eine Entscheidung neu aufzurollen, die Sie schon getroffen haben.",
    whatCanGoWrong: "Eine Runde, in der NIEMAND geantwortet hat, geht nie durch. Ein leeres Ergebnis ist das Fehlen von Belegen, nicht der Beleg für ein Fehlen: das Gate ruft stattdessen einen Menschen. Das ist der einzige Fall, in dem „keine Befunde“ nicht „freigegeben“ heißen darf.",
  },
  "where-reviewers-run": {
    title: "Unter der Haube: wo ein Reviewer wirklich läuft",
    whatItIs: "Die Code-Stufe gibt der Runde EIN git-worktree, festgenagelt auf den Commit des Branches, nur lesbar. Die Plan-Stufe gibt jedem Reviewer stattdessen ein LEERES Verzeichnis.",
    why: "Gibt man einer agentischen CLI ein Repository und einen Plan, der Dateien nennt, geht sie diese lesen. Gemessen: acht Minuten und immer noch am Laufen — bei einem Dokument von fünfzehn Kilobyte. Die Aufgabe dort ist, das DOKUMENT zu beurteilen; das Repository braucht die Code-Stufe.",
    setup: "Nichts einzustellen. Die Worktrees liegen im Datenverzeichnis des Servers und werden beim Öffnen einer Sitzung aufgeräumt, sodass eine abgebrochene Runde nichts hinterlässt.",
    usage: "Was das leere Verzeichnis kostet, im Klartext: ein Plan-Reviewer kann nicht prüfen, ob ein Verweis der Form `file.cs:line` im Plan echt ist. Diese Prüfung stand im Plan-Prompt ohnehin nie, und sie mit der zehnfachen Laufzeit zu erkaufen ist der falsche Tausch für ein Gate, an dem ein Mensch wartet.",
    whatCanGoWrong: "Der einzige Wiederholungsversuch eines Reviewers läuft aus demselben Grund ebenfalls im leeren Verzeichnis: die Reparatur bittet um die Antwort im Schema, nicht um neue Recherche. Genau das erneute Aushändigen eines Checkouts kostete in einer von drei Code-Runden einen Reviewer.",
  },
  "when-a-reviewer-fails": {
    title: "Unter der Haube: was passiert, wenn ein Reviewer scheitert",
    whatItIs: "Sechs benannte Ausgänge und niemals eine stille Null: geantwortet, ins Timeout gelaufen, mit Fehlercode beendet, ins Ratenlimit gelaufen, nicht startbar, oder mit etwas geantwortet, das sich nicht parsen lässt. Eine Runde, die mit vier von sechs Reviewern durchlief, sagt genau das — mit Namen.",
    why: "Ein Panel, das nicht reviewt hat, ist kein Panel, das zugestimmt hat. Jede unvollständige Runde meldet sich als unvollständig, und der Reviewer-Satz im Panel nennt, wer scheiterte und warum.",
    setup: "Nichts einzustellen. Ein Reviewer im Ratenlimit wird nach einer Pause genau einmal wiederholt — es sei denn, der Hersteller hat gesagt, das Limit gelte für den TAG, und das heilt keine Wiederholung.",
    usage: "Eine Absage trägt die eigenen Worte der CLI, nach Inhalt gewählt und nicht nach Position: die erste Zeile, die einen Fehler ankündigt, vorbei an Stack-Frames und Versionsbannern. Für fünf bekannte Absagen — geschlossene CLI, nicht vertrautes Verzeichnis, fehlende Binärdatei für die Plattform — wird gesagt, WAS ZU TUN IST, statt was gedruckt wurde.",
    whatCanGoWrong: "Eine Antwort, die sich nicht parsen ließ, wird unter `unparseable/` im Datenverzeichnis gespeichert, und die Absage nennt die Datei. Das kam daher, dass dieselbe Antwort, von Hand nachgestellt, sauber durchlief — die Meldung nannte also ein Symptom, das sich nicht untersuchen ließ.",
  },
  "settings-and-the-server": {
    title: "Unter der Haube: wie eine Einstellung den Server erreicht",
    whatItIs: "Das Panel schreibt Ihre Einstellungen in eine Datei im Datenverzeichnis des Servers, und der Server liest diese Datei neu, sobald sie sich ändert.",
    why: "Früher erreichten Einstellungen den Server nur im eingefügten Konfigurationsblock, und jede Änderung einer Schwelle wurde zur Prozedur: Block kopieren, Client-Konfiguration finden, einfügen, neu starten. Und sie galten nur beim Start — ein Bruch, der von beiden Seiten unsichtbar war, weil das Panel sofort speichert und das auch so sagt.",
    setup: "Nichts einzustellen. Eine Änderung im Panel gilt ab der NÄCHSTEN Runde: kein Neustart, kein erneutes Einfügen.",
    usage: "Eine Variable in der Konfiguration des Assistenten schlägt die Datei weiterhin: sie ist spezifischer als eine Datei, die jedes Fenster überschreiben kann.\n\nDas Panel schreibt nur, was von den Voreinstellungen ABWEICHT — eine Einstellung auf ihre Voreinstellung zurückzusetzen entfernt sie also aus der Datei, statt sie festzuschreiben.",
    whatCanGoWrong: "Eine halb geschriebene Datei lässt die letzte funktionierende Konfiguration stehen. Ein zerrissener Lesevorgang mit leerer Herstellerliste hätte jeden Reviewer scheitern lassen und wäre von einem Panel gemeldet worden, das mit sich selbst einig ist.",
  },
  "the-audit-log": {
    title: "Unter der Haube: das Audit-Log",
    whatItIs: "Eine Logdatei pro Serverlauf, neben der installierten Binärdatei, unter `logs/<Tag>/`. Darin die Besetzung jeder Runde, Start und Antwort jedes Reviewers mit Tokens und Geld, jede Absage als Warnung mit Grund, und jeder Befund mit seiner Herkunft.",
    why: "Die Rundenzusammenfassung ist bewusst ein Satz, und ein Satz beantwortet nicht „warum ist dieser Reviewer gescheitert“. Diese Frage kam an einem echten Gate zweimal auf, und beide Male gab es nichts zu antworten.",
    setup: "Nichts einzustellen. Die Stufen kommen aus der Konfiguration statt aus Aufrufstellen, und je Lauf entsteht eine neue Datei — nicht je Tag, weil fast immer gefragt wird, was JENER Lauf getan hat.",
    usage: "Auf Debug-Stufe wird die exakte Kommandozeile jedes Reviewers geschrieben — das ist der Unterschied zwischen „wissen, dass der Hersteller gefragt wurde“ und „den Befehl ins Terminal einfügen und dieselbe Absage sehen“.",
    whatCanGoWrong: "Das Log ist der einzige Ort, an dem manches überhaupt festgehalten wird. Es rotiert nicht und wird nicht beschnitten: ein Jahr dichter Arbeit ist ein Ordner kleiner Dateien — kein Problem, aber aufräumen müssen Sie ihn.",
  },
};
