export const SECURITY_HELP = {
  id: 'security-lane',
  en: {
    title: 'Security lane: extra reviewer and prompt pairs',
    whatItIs: 'An optional set of security reviews beside ordinary code and feature reviews. Each pair selects an existing reviewer and a redteam prompt. It is off by default and requires an ordinary gate.',
    why: 'A targeted prompt can examine a security boundary separately while preserving its findings and evidence in the same review history.',
    setup: 'Open Settings → Security lane and enable the lane. Every prompt is a card: green for a shipped prompt, orange once you change its text or its conditions (Restore default puts it back), purple for your own. Tick a reviewer on a card to pair them. redteam-general comes first and runs on every code change while a reviewer is ticked. The other shipped prompts are presets — authorization, SQL, concurrency, auth tokens, SSRF, webhooks, files, commands, deserialization, secrets, prompt injection and XSS — and run when changed code matches their conditions, folded under each card beside the sources they prioritize; a preset with no condition does not run. Make your own prompt with + New custom prompt: it asks for a redteam- name, creates prompts/<name>.md in your data directory and opens it, and its card names that file and says when it has no usable text. Edit prompt text opens the file again; Remove custom prompt takes the prompt and its pairs out of the lane and leaves the file on disk. Each pair takes stages, a source mode and a context token budget; + Add reviewer / prompt pair and Remove pair are buttons. The defaults are two rounds and zero allowed major/blocking findings. Shipped prompts are versioned in src_mcp/src/prompts/redteam-*.md; Edit local prompt override opens an optional file in your data directory and does not change the Git default.',
    usage: 'The lane shares existing concurrency limits, keeps a separate identity for each pair, and continues until its round budget is spent. A reviewer row may be enabled only for security. Reproduction evidence appears in the rounds log and is never executed. A major/blocking finding without complete reproduction evidence is capped at minor before findings are merged.',
    whatCanGoWrong: 'An older MCP server cannot run the lane; update to 0.41.0 or later. redteam-general runs on code changes only from MCP 0.43.0; an older server runs it on every change, documentation included. If its card says it has stored conditions from before it shipped, press Clear stored conditions — until then an older server runs it only when they match. Missing prompt text, unsupported Team runtime, invalid configuration and failed reviews are reported. A malformed coai.securityLane in your settings JSON turns the lane off; the Security lane tab says which part is wrong, and you correct it there. Context is bounded and omissions are named. Local input coverage remains unverified even if a model answers successfully. A silent lane does not certify a security review, and a successful lane answer cannot replace a failed ordinary reviewer.',
  },
};
